module.exports = {
  NODE_ENV: process.env.NODE_ENV || 'production',
  MONGODB: {
    CONNECTION_STRING: process.env.MONGODB_CONNECTION_STRING,
    DB_NAME: process.env.MONGODB_DB_NAME,
    LOG_COLLECTION: process.env.MONGODB_LOG_COLLECTION,
    USERS_COLLECTION: process.env.MONGODB_USERS_COLLECTION
  },
  APPREG: {
    CLIENT_ID: process.env.APPREG_CLIENT_ID,
    CLIENT_SECRET: process.env.APPREG_CLIENT_SECRET,
    TENANT_ID: process.env.APPREG_TENANT_ID
  },
  AUTHENTICATION_ADMINISTRATOR: {
    USERNAME: process.env.AUTHENTICATION_ADMINISTRATOR_USERNAME,
    PASSWORD: process.env.AUTHENTICATION_ADMINISTRATOR_PASSWORD,
    SCOPE: process.env.AUTHENTICATION_ADMINISTRATOR_SCOPE
  },
  GRAPH: {
    SSN_EXTENSION_ATTRIBUTE: process.env.GRAPH_SSN_EXTENSION_ATTRIBUTE,
    EMPLOYEE_UPN_SUFFIX: process.env.GRAPH_EMPLOYEE_UPN_SUFFIX,
    STUDENT_UPN_SUFFIX: process.env.GRAPH_STUDENT_UPN_SUFFIX,
    SCOPE: process.env.GRAPH_SCOPE || 'https://graph.microsoft.com/.default',
    URL: process.env.GRAPH_URL || 'https://graph.microsoft.com'
  },
  ENTRA_PWD: {
    CLIENT_ID: process.env.ENTRA_PWD_CLIENT_ID,
    ClIENT_SECRET: process.env.ENTRA_PWD_CLIENT_SECRET,
    TENANT_ID: process.env.ENTRA_PWD_TENANT_ID,
    ClIENT_REDIRECT_URI: process.env.ENTRA_PWD_CLIENT_REDIRECT_URI,
    CLIENT_POST_LOGOUT_REDIRECT_URI: process.env.ENTRA_PWD_CLIENT_POST_LOGOUT_REDIRECT_URI
  },
  ENTRA_MFA: {
    CLIENT_ID: process.env.ENTRA_MFA_CLIENT_ID,
    ClIENT_SECRET: process.env.ENTRA_MFA_CLIENT_SECRET,
    TENANT_ID: process.env.ENTRA_MFA_TENANT_ID,
    ClIENT_REDIRECT_URI: process.env.ENTRA_MFA_CLIENT_REDIRECT_URI,
    CLIENT_POST_LOGOUT_REDIRECT_URI: process.env.ENTRA_MFA_CLIENT_POST_LOGOUT_REDIRECT_URI
  },
  ENTRA_STATISTICS: {
    CLIENT_ID: process.env.ENTRA_STATISTICS_CLIENT_ID,
    ClIENT_SECRET: process.env.ENTRA_STATISTICS_CLIENT_SECRET,
    TENANT_ID: process.env.ENTRA_STATISTICS_TENANT_ID,
    ClIENT_REDIRECT_URI: process.env.ENTRA_STATISTICS_CLIENT_REDIRECT_URI,
    CLIENT_POST_LOGOUT_REDIRECT_URI: process.env.ENTRA_STATISTICS_CLIENT_POST_LOGOUT_REDIRECT_URI
  },
  IDPORTEN: {
    CLIENT_ID: process.env.IDPORTEN_CLIENT_ID,
    ClIENT_SECRET: process.env.IDPORTEN_CLIENT_SECRET,
    ClIENT_REDIRECT_URI: process.env.IDPORTEN_CLIENT_REDIRECT_URI,
    CLIENT_POST_LOGOUT_REDIRECT_URI: process.env.IDPORTEN_CLIENT_POST_LOGOUT_REDIRECT_URI,
    WELL_KNOWN_ENDPOINT: process.env.IDPORTEN_WELL_KNOWN_ENDPOINT
  },
  KRR: {
    URL: process.env.KRR_URL,
    KEY: process.env.KRR_KEY
  },
  SMS: {
    URL: process.env.SMS_URL,
    KEY: process.env.SMS_KEY,
    SENDER: process.env.SMS_SENDER
  },
  STATISTICS: {
    URL: process.env.STATISTICS_URL,
    KEY: process.env.STATISTICS_KEY
  },
  DEMO_MODE: {
    ENABLED: (process.env.DEMO_MODE_ENABLED && process.env.DEMO_MODE_ENABLED === 'true') || false,
    GLOBAL_MOCK_RESET_PASSWORD: (process.env.DEMO_MODE_GLOBAL_MOCK_RESET_PASSWORD && process.env.DEMO_MODE_GLOBAL_MOCK_RESET_PASSWORD === 'true') || false,
    DEMO_USERS: (process.env.DEMO_MODE_DEMO_USERS && JSON.parse(process.env.DEMO_MODE_DEMO_USERS)) || false
  },
  BAD_WORDS: (process.env.BAD_WORDS && process.env.BAD_WORDS.split(',')) || []
}
